# Generated by Django 5.0.3 on 2024-03-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_tag_alter_category_options_alter_joke_slug_joke_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jokes.category'),
        ),
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
